src/TrollMarketWeb/Controllers/CartController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TrollMarketWeb;
[Authorize(Roles ="Buyer")]
public class CartController:Controller
{
    private readonly CartService _service;

    public CartController(CartService service)
    {
        _service = service;
    }

    [HttpGet]
    public IActionResult Index(){
        var user = User.FindFirstValue("username");
        var role = User.Claims.ToList()[1].Value;
        System.Console.WriteLine(user);
        ViewData["Username"] = user;
        ViewData["Role"] = role;
        var viewModel = _service.Get(user);
        return View("Index", viewModel);
    }
}

src/TrollMarketWeb/Controllers/HistoryController.cs
using System.Runtime.InteropServices;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TrollMarketWeb;

[Authorize(Roles = "Admin")]
public class HistoryController : Controller
{
    private readonly HistoryService _service;

    public HistoryController(HistoryService service)
    {
        _service = service;
    }

    public IActionResult Index(int pageNumber=1, int pageSize=5, string sellerName="", string buyerName=""){
        var user = User.FindFirstValue("username");
        var role = User.Claims.ToList()[1].Value;
        ViewData["Username"] = user;
        ViewData["Role"] = role;
        var model = _service.Get(pageNumber, pageSize, sellerName, buyerName);
        return View(model);
    }
}

src/TrollMarketWeb/Controllers/ProfileController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TrollMarketWeb;

[Authorize(Roles ="Buyer,Seller")]
public class ProfileController : Controller
{
    private readonly UserService _service;

    public ProfileController(UserService service)
    {
        _service = service;
    }

    // [HttpGet("Profile/{username}")]
    public IActionResult Index(){
        var user = User.FindFirstValue("username");
        var role = User.Claims.ToList()[1].Value;
        ViewData["Username"] = user;
        ViewData["Role"] = role;
        var viewModel = _service.Get(user);
        return View("Index",viewModel);
    }
}

src/TrollMarketWeb/Controllers/ShopController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TrollMarketWeb;

[Authorize(Roles ="Buyer")]
public class ShopController : Controller
{
    private readonly ShopService _service;

    public ShopController(ShopService service)
    {
        _service = service;
    }

    public IActionResult Index(int pageNumber=1, string productName="", string categoryName="", string description=""){
        var user = User.FindFirstValue("username");
        var role = User.Claims.ToList()[1].Value;
        ViewData["Username"] = user;
        ViewData["Role"] = role;
        var viewModel = _service.GetProduct(pageNumber,3,productName,categoryName,description);
        return View(viewModel);
    }
}

src/TrollMarketWeb/Views/Shared/_Header.cshtml
<header>
    <div class="header-content">
            <div class="bread-crumbs">
            <a class="toggle-menu" href="javascript:;"><i class="fas fa-bars"></i></a>
            <span>Troll Market</span>
        </div>
        <div class="user-wrapper">
            <div class="user">
                <p>Welcome, @ViewData["Username"]</p>
                <span class="role" hidden>@ViewData["Role"]</span>
            </div>
            <div class="sign-out">
                <form asp-controller="Auth" asp-action="Logout" method="POST">
                    <input type="hidden" />
                    <button type="submit" id="logout">Sign Out</button>
                </form>
            </div>
        </div>
    </div>
</header>

src/TrollMarketWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Troll Market</title>
    <link rel="stylesheet" href="~/css/style.css"/>
    @* <link rel="stylesheet" href="~/css/site.css">
    <script src="~/JS/site.js" defer></script> *@
</head>
<body class="main-body">
    <partial name="_Header"></partial>
    <partial name="_Navigasi"></partial>
    @RenderSection("Breadcrumbs", false)
	<main>
        @RenderBody()
	</main>
</body>
</html>

src/TrollMarketWeb/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/style-login.css">
    <title>TrollMarket-Login</title>
</head>
<body>
    @RenderBody()
</body>
</html>

src/TrollMarketWeb/Views/Shared/_Navigasi.cshtml
<nav>
    <ul>
        <li><a asp-controller="Dashboard" asp-action="Index" class="home">Home</a></li>
        <li><a asp-controller="Profile" asp-action="Index" class="profile">Profile</a></li>
        <li><a asp-controller="Shop" asp-action="Index" class="shop">Shop</a></li>
        <li><a asp-controller="Merchandise" asp-action="Index" class="merchandise">Merchindise</a></li>
        <li><a asp-controller="Shipper" asp-action="Index" class="shipment">Shipment</a></li>
        <li><a asp-controller="Cart" asp-action="Index" class="mycart">My Cart</a></li>
        <li><a asp-controller="Admin" asp-action="Index" class="admin">Admin</a></li>
        <li><a asp-controller="History" asp-action="Index" class="history">History</a></li>
    </ul>
</nav>